# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 161, 551))
        self.treeWidget.setObjectName("treeWidget")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(10, 570, 161, 25))
        self.saveButton.setObjectName("saveButton")
        self.Stack = QtWidgets.QStackedWidget(self.centralwidget)
        self.Stack.setGeometry(QtCore.QRect(180, 10, 851, 681))
        self.Stack.setObjectName("Stack")
        self.Alunos = QtWidgets.QWidget()
        self.Alunos.setObjectName("Alunos")
        self.ageEdit = QtWidgets.QLineEdit(self.Alunos)
        self.ageEdit.setGeometry(QtCore.QRect(90, 60, 113, 25))
        self.ageEdit.setObjectName("ageEdit")
        self.friendsEdit = QtWidgets.QTextEdit(self.Alunos)
        self.friendsEdit.setGeometry(QtCore.QRect(90, 230, 271, 291))
        self.friendsEdit.setObjectName("friendsEdit")
        self.nameLabel = QtWidgets.QLabel(self.Alunos)
        self.nameLabel.setGeometry(QtCore.QRect(20, 20, 67, 17))
        self.nameLabel.setObjectName("nameLabel")
        self.jobEdit = QtWidgets.QLineEdit(self.Alunos)
        self.jobEdit.setGeometry(QtCore.QRect(90, 110, 271, 25))
        self.jobEdit.setObjectName("jobEdit")
        self.ageLabel = QtWidgets.QLabel(self.Alunos)
        self.ageLabel.setGeometry(QtCore.QRect(20, 60, 67, 17))
        self.ageLabel.setObjectName("ageLabel")
        self.friendsLabel = QtWidgets.QLabel(self.Alunos)
        self.friendsLabel.setGeometry(QtCore.QRect(20, 230, 67, 17))
        self.friendsLabel.setObjectName("friendsLabel")
        self.interestsLabel = QtWidgets.QLabel(self.Alunos)
        self.interestsLabel.setGeometry(QtCore.QRect(20, 170, 67, 17))
        self.interestsLabel.setObjectName("interestsLabel")
        self.jobLabel = QtWidgets.QLabel(self.Alunos)
        self.jobLabel.setGeometry(QtCore.QRect(20, 120, 67, 17))
        self.jobLabel.setObjectName("jobLabel")
        self.interestsEdit = QtWidgets.QLineEdit(self.Alunos)
        self.interestsEdit.setGeometry(QtCore.QRect(90, 170, 271, 25))
        self.interestsEdit.setObjectName("interestsEdit")
        self.nameEdit = QtWidgets.QLineEdit(self.Alunos)
        self.nameEdit.setGeometry(QtCore.QRect(90, 20, 271, 25))
        self.nameEdit.setObjectName("nameEdit")
        self.studentRoomLabel = QtWidgets.QLabel(self.Alunos)
        self.studentRoomLabel.setGeometry(QtCore.QRect(220, 60, 67, 17))
        self.studentRoomLabel.setObjectName("studentRoomLabel")
        self.studentRoomEdit = QtWidgets.QLineEdit(self.Alunos)
        self.studentRoomEdit.setGeometry(QtCore.QRect(280, 60, 81, 25))
        self.studentRoomEdit.setObjectName("studentRoomEdit")
        self.checkBox = QtWidgets.QCheckBox(self.Alunos)
        self.checkBox.setGeometry(QtCore.QRect(20, 560, 171, 23))
        self.checkBox.setObjectName("checkBox")
        self.studentNotes = QtWidgets.QTextEdit(self.Alunos)
        self.studentNotes.setGeometry(QtCore.QRect(520, 20, 321, 501))
        self.studentNotes.setObjectName("studentNotes")
        self.studentNotesLabel = QtWidgets.QLabel(self.Alunos)
        self.studentNotesLabel.setGeometry(QtCore.QRect(410, 20, 101, 17))
        self.studentNotesLabel.setObjectName("studentNotesLabel")
        self.Stack.addWidget(self.Alunos)
        self.Sala = QtWidgets.QWidget()
        self.Sala.setObjectName("Sala")
        self.roomLabel = QtWidgets.QLabel(self.Sala)
        self.roomLabel.setGeometry(QtCore.QRect(30, 20, 67, 17))
        self.roomLabel.setObjectName("roomLabel")
        self.roomEdit = QtWidgets.QLineEdit(self.Sala)
        self.roomEdit.setGeometry(QtCore.QRect(90, 20, 71, 25))
        self.roomEdit.setObjectName("roomEdit")
        self.notesEdit = QtWidgets.QTextEdit(self.Sala)
        self.notesEdit.setGeometry(QtCore.QRect(490, 80, 291, 521))
        self.notesEdit.setObjectName("notesEdit")
        self.notesLabel = QtWidgets.QLabel(self.Sala)
        self.notesLabel.setGeometry(QtCore.QRect(400, 90, 91, 17))
        self.notesLabel.setObjectName("notesLabel")
        self.attributesLabel = QtWidgets.QLabel(self.Sala)
        self.attributesLabel.setGeometry(QtCore.QRect(0, 90, 111, 21))
        self.attributesLabel.setObjectName("attributesLabel")
        self.attributesEdit = QtWidgets.QTextEdit(self.Sala)
        self.attributesEdit.setGeometry(QtCore.QRect(90, 80, 271, 521))
        self.attributesEdit.setObjectName("attributesEdit")
        self.dateTimeLabel = QtWidgets.QLabel(self.Sala)
        self.dateTimeLabel.setGeometry(QtCore.QRect(190, 20, 81, 17))
        self.dateTimeLabel.setObjectName("dateTimeLabel")
        self.dateTimeEdit = QtWidgets.QLineEdit(self.Sala)
        self.dateTimeEdit.setGeometry(QtCore.QRect(280, 20, 241, 25))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.classTeacherLabel = QtWidgets.QLabel(self.Sala)
        self.classTeacherLabel.setGeometry(QtCore.QRect(540, 20, 81, 17))
        self.classTeacherLabel.setObjectName("classTeacherLabel")
        self.classTeacherEdit = QtWidgets.QLineEdit(self.Sala)
        self.classTeacherEdit.setGeometry(QtCore.QRect(620, 20, 161, 25))
        self.classTeacherEdit.setObjectName("classTeacherEdit")
        self.Stack.addWidget(self.Sala)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRoom = QtWidgets.QAction(MainWindow)
        self.actionRoom.setObjectName("actionRoom")
        self.actionStudent = QtWidgets.QAction(MainWindow)
        self.actionStudent.setObjectName("actionStudent")
        self.menuNew.addAction(self.actionRoom)
        self.menuNew.addAction(self.actionStudent)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Escola Virtual"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Classes"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.nameLabel.setText(_translate("MainWindow", "Nome:"))
        self.ageLabel.setText(_translate("MainWindow", "Idade:"))
        self.friendsLabel.setText(_translate("MainWindow", "Friends:"))
        self.interestsLabel.setText(_translate("MainWindow", "Interests:"))
        self.jobLabel.setText(_translate("MainWindow", "Job:"))
        self.studentRoomLabel.setText(_translate("MainWindow", "Room:"))
        self.checkBox.setText(_translate("MainWindow", "Necessidade Especial?"))
        self.studentNotesLabel.setText(_translate("MainWindow", "Observações:"))
        self.roomLabel.setText(_translate("MainWindow", "Room:"))
        self.notesLabel.setText(_translate("MainWindow", "Notes:"))
        self.attributesLabel.setText(_translate("MainWindow", "Attributes:"))
        self.dateTimeLabel.setText(_translate("MainWindow", "Date/Time:"))
        self.classTeacherLabel.setText(_translate("MainWindow", "Professor:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))
        self.actionRoom.setText(_translate("MainWindow", "Room"))
        self.actionStudent.setText(_translate("MainWindow", "Student"))


